# -*- coding: utf-8 -*-
"""tenserflow model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nQx0PNy2G44rjsTmF_9D6wDm0L1SsHH
"""

from google.colab import drive
drive.mount('/content/drive')

pip install scikit-learn==1.7.1

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

import pandas as pd
import numpy as np


# Load dataset
file_path = '/content/drive/My Drive/CICIDS2017_merged_cleaned.csv'
df = pd.read_csv(file_path, encoding='latin1', low_memory=False)


# Drop unnamed or irrelevant columns if any
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Strip whitespace from column names
df.columns = df.columns.str.strip()

# Strip whitespace and decode strange characters from string/object columns
df = df.applymap(lambda x: str(x).encode('utf-8', 'ignore').decode('utf-8', 'ignore') if isinstance(x, str) else x)

# View label values
print("Label unique values:", df['Label'].unique())

# Binary classification: Make all non-BENIGN labels into ATTACK
df['Label'] = df['Label'].apply(lambda x: 'BENIGN' if x.upper() == 'BENIGN' else 'ATTACK')

# Encode: BENIGN = 0, ATTACK = 1
df['Label'] = df['Label'].map({'BENIGN': 0, 'ATTACK': 1})

drop_cols=['Flow ID','Source IP','Destination IP','Timestamp']
df.drop(columns=drop_cols, inplace=True)

df.head()
# Remove object-type (string) columns except Label
non_numeric = df.select_dtypes(include=['object']).columns.tolist()
non_numeric = [col for col in non_numeric if col != 'Label']
df = df.drop(columns=non_numeric)

print(df['Protocol'].values)
df.head()

# Convert all remaining columns to numeric (in case some are still weird)
for col in df.columns:
    if col != 'Label':
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Replace inf/-inf and NaN with 0
df = df.replace([np.inf, -np.inf], np.nan).fillna(0)

# Split features and labels
X = df.drop(columns=['Label'])
y = df['Label']

# Ensure all features are float32
X = X.astype(np.float32)

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, shuffle=True
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')  # binary classification
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy', tf.keras.metrics.AUC(name='auc')])

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(X_train, y_train, epochs=10, batch_size=1024, validation_split=0.3)
import joblib
joblib.dump(scaler,'dl_scaler4.joblib')
model.save('dl_model4.h5')
model.save('dl_model4.keras')
print(X.columns.tolist())

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")

y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype("int32")

print(df['Protocol'].tolist())

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm).plot()
print("Confusion matrix: ",cm)

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_test, model.predict(X_test))
print("ROC-AUC Score:", roc_auc)

print(X.columns.tolist())

from tensorflow.keras.models import load_model

# Load from .h5
model = load_model("dl_model.h5")

# Save in new format
model.save("dl_model.keras")

import tensorflow as tf
print(tf.__version__)